<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        /* Error：普通异常 。与thorw语句和try/catch语句一起使用，属性name可以读写异常类型，message属性可以读写详细的错误信息。
            EvalError：不正确使用eval()方法时抛出
            SyntaxError：出现语法错误时抛出
            RangeError：数字超出合法范围之抛出
            ReferenceError：读取不存在的变量时抛出
            TypeError：值的类型发生错误的时候抛出
            URIError：URI编码和解码错误时抛出 */

        /*         try{
                    console.log(a);
                }
                catch(e){
                    console.log("catch");
                    console.log(e);
                    console.log(e.name)
                    console.log(e.message)
                } */
/*         try {
            console.log("try");
            throw new Error("你是不是没有定义变量");
        } catch (e) {
            console.log("catch")
            console.log(e);
            console.log(e.name);
            console.log(e.message);
        } */
        var a=9;
        if(a>4){
            var userError="print";
            throw new SyntaxError(userError);
        }
    </script>
</body>

</html>